import { Category } from './types';

const BASE_CATEGORIES: Category[] = [
  {
    id: 'objects',
    name: 'Do vat hang ngay',
    icon: 'home',
    pairs: [
      { citizen: 'Gau bong', imposter_hint: 'Bup be', difficulty: 'VERY_EASY' },
      { citizen: 'Cai coc', imposter_hint: 'Cai bat', difficulty: 'VERY_EASY' },
      { citizen: 'Ban chai rang', imposter_hint: 'Khan mat', difficulty: 'EASY' },
      { citizen: 'Cap sach', imposter_hint: 'Hop but', difficulty: 'EASY' },
      { citizen: 'Den hoc', imposter_hint: 'Den ngu', difficulty: 'EASY' },
      { citizen: 'Chia khoa', imposter_hint: 'O khoa', difficulty: 'EASY' },
      { citizen: 'May giat', imposter_hint: 'Tu lanh', difficulty: 'EASY' },
      { citizen: 'Lo vi song', imposter_hint: 'Noi com dien', difficulty: 'HARD' },
      { citizen: 'Tivi', imposter_hint: 'May tinh', difficulty: 'EASY' },
      { citizen: 'Quat tran', imposter_hint: 'Dieu hoa', difficulty: 'HARD' },
      { citizen: 'Binh nuoc', imposter_hint: 'Am sieu toc', difficulty: 'EASY' },
      { citizen: 'Kinh mat', imposter_hint: 'Kinh ram', difficulty: 'EASY' },
    ],
  },
  {
    id: 'foods',
    name: 'Am thuc',
    icon: 'pizza',
    pairs: [
      { citizen: 'Pho', imposter_hint: 'Bun bo', difficulty: 'HARD' },
      { citizen: 'Com tam', imposter_hint: 'Com ga', difficulty: 'EASY' },
      { citizen: 'Banh mi', imposter_hint: 'Hamburger', difficulty: 'EASY' },
      { citizen: 'Tra sua', imposter_hint: 'Sua tuoi', difficulty: 'EASY' },
      { citizen: 'Kem oc que', imposter_hint: 'Sua chua', difficulty: 'VERY_EASY' },
      { citizen: 'Pizza', imposter_hint: 'Mi y', difficulty: 'EASY' },
      { citizen: 'Lau', imposter_hint: 'Nuong', difficulty: 'HARD' },
      { citizen: 'Khoai tay chien', imposter_hint: 'Ga ran', difficulty: 'VERY_EASY' },
      { citizen: 'Xuc xich', imposter_hint: 'Lap xuong', difficulty: 'EASY' },
      { citizen: 'Dua hau', imposter_hint: 'Dua luoi', difficulty: 'VERY_EASY' },
      { citizen: 'Muoi', imposter_hint: 'Duong', difficulty: 'HARD' },
      { citizen: 'Ca phe sua', imposter_hint: 'Tra dao', difficulty: 'EASY' },
    ],
  },
  {
    id: 'animals',
    name: 'Dong vat',
    icon: 'paw',
    pairs: [
      { citizen: 'Con meo', imposter_hint: 'Con ho', difficulty: 'VERY_EASY' },
      { citizen: 'Con cho', imposter_hint: 'Con soi', difficulty: 'EASY' },
      { citizen: 'Con voi', imposter_hint: 'Con ha ma', difficulty: 'EASY' },
      { citizen: 'Con khi', imposter_hint: 'Con vuon', difficulty: 'EASY' },
      { citizen: 'Con ga', imposter_hint: 'Con vit', difficulty: 'VERY_EASY' },
      { citizen: 'Con tho', imposter_hint: 'Con chuot', difficulty: 'VERY_EASY' },
      { citizen: 'Ca map', imposter_hint: 'Ca voi', difficulty: 'EASY' },
      { citizen: 'Con kien', imposter_hint: 'Con gian', difficulty: 'HARD' },
      { citizen: 'Con ong', imposter_hint: 'Con buom', difficulty: 'HARD' },
      { citizen: 'Rua', imposter_hint: 'Oc sen', difficulty: 'EASY' },
      { citizen: 'Con ran', imposter_hint: 'Con luon', difficulty: 'HARD' },
      { citizen: 'Con huou cao co', imposter_hint: 'Con ngua van', difficulty: 'HARD' },
    ],
  },
  {
    id: 'entertainment',
    name: 'Giai tri va phim anh',
    icon: 'film',
    pairs: [
      { citizen: 'Doraemon', imposter_hint: 'Nobita', difficulty: 'VERY_EASY' },
      { citizen: 'Nguoi nhen', imposter_hint: 'Nguoi sat', difficulty: 'EASY' },
      { citizen: 'Elsa', imposter_hint: 'Anna', difficulty: 'VERY_EASY' },
      { citizen: 'YouTube', imposter_hint: 'TikTok', difficulty: 'EASY' },
      { citizen: 'Rap chieu phim', imposter_hint: 'San khau kich', difficulty: 'HARD' },
      { citizen: 'Ca si', imposter_hint: 'Dien vien', difficulty: 'EASY' },
      { citizen: 'Harry Potter', imposter_hint: 'Chua te nhan', difficulty: 'HARD' },
      { citizen: 'Marvel', imposter_hint: 'DC Comics', difficulty: 'HARD' },
      { citizen: 'Superman', imposter_hint: 'Batman', difficulty: 'EASY' },
      { citizen: 'Netflix', imposter_hint: 'Disney Plus', difficulty: 'EASY' },
      { citizen: 'Kpop', imposter_hint: 'Vpop', difficulty: 'EASY' },
      { citizen: 'Guitar', imposter_hint: 'Piano', difficulty: 'EASY' },
    ],
  },
  {
    id: 'knowledge',
    name: 'Kien thuc va doi song',
    icon: 'book',
    pairs: [
      { citizen: 'Bang den', imposter_hint: 'Vien phan', difficulty: 'VERY_EASY' },
      { citizen: 'But chi', imposter_hint: 'But bi', difficulty: 'VERY_EASY' },
      { citizen: 'Bac si', imposter_hint: 'Y ta', difficulty: 'EASY' },
      { citizen: 'Cong an', imposter_hint: 'Bo doi', difficulty: 'EASY' },
      { citizen: 'Giao vien', imposter_hint: 'Giang vien', difficulty: 'HARD' },
      { citizen: 'Sach giao khoa', imposter_hint: 'Tu dien', difficulty: 'EASY' },
      { citizen: 'Ban do', imposter_hint: 'Qua dia cau', difficulty: 'HARD' },
      { citizen: 'Tien mat', imposter_hint: 'The ngan hang', difficulty: 'EASY' },
      { citizen: 'Ho chieu', imposter_hint: 'Visa', difficulty: 'HARD' },
      { citizen: 'Email', imposter_hint: 'Thu tay', difficulty: 'EASY' },
      { citizen: 'Wifi', imposter_hint: '4G', difficulty: 'EASY' },
      { citizen: 'Robot', imposter_hint: 'Tri tue nhan tao', difficulty: 'HARD' },
    ],
  },
  {
    id: 'sports',
    name: 'The thao',
    icon: 'ball',
    pairs: [
      { citizen: 'Da bong', imposter_hint: 'Da cau', difficulty: 'VERY_EASY' },
      { citizen: 'Boi loi', imposter_hint: 'Lan bien', difficulty: 'EASY' },
      { citizen: 'Cau long', imposter_hint: 'Tennis', difficulty: 'EASY' },
      { citizen: 'Bong ro', imposter_hint: 'Bong chuyen', difficulty: 'EASY' },
      { citizen: 'Chay bo', imposter_hint: 'Di bo', difficulty: 'VERY_EASY' },
      { citizen: 'Dap xe', imposter_hint: 'Dua xe may', difficulty: 'EASY' },
      { citizen: 'Tap gym', imposter_hint: 'Yoga', difficulty: 'HARD' },
      { citizen: 'Boxing', imposter_hint: 'Vat', difficulty: 'HARD' },
      { citizen: 'Golf', imposter_hint: 'Bida', difficulty: 'HARD' },
      { citizen: 'Co vua', imposter_hint: 'Co tuong', difficulty: 'EASY' },
      { citizen: 'Ban cung', imposter_hint: 'Ban sung', difficulty: 'HARD' },
      { citizen: 'Nhay cao', imposter_hint: 'Nhay xa', difficulty: 'HARD' },
    ],
  },
];

const BASE_CHARADES_CATEGORIES: Category[] = [
  {
    id: 'actions',
    name: 'Hanh dong',
    icon: 'run',
    pairs: [
      { citizen: 'Danh rang', imposter_hint: 'Rua mat', difficulty: 'VERY_EASY' },
      { citizen: 'Quet nha', imposter_hint: 'Lau nha', difficulty: 'VERY_EASY' },
      { citizen: 'Nau an', imposter_hint: 'Rua bat', difficulty: 'EASY' },
      { citizen: 'Ngu gat', imposter_hint: 'Ngap', difficulty: 'EASY' },
      { citizen: 'Boi loi', imposter_hint: 'Cheo thuyen', difficulty: 'EASY' },
      { citizen: 'Chup anh', imposter_hint: 'Livestream', difficulty: 'HARD' },
      { citizen: 'Tap gym', imposter_hint: 'Chay bo', difficulty: 'EASY' },
      { citizen: 'Di mua sam', imposter_hint: 'Di ship hang', difficulty: 'HARD' },
      { citizen: 'Lai o to', imposter_hint: 'Lai xe may', difficulty: 'VERY_EASY' },
      { citizen: 'Nhay mua', imposter_hint: 'Tap the duc', difficulty: 'EASY' },
      { citizen: 'Khoc nhe', imposter_hint: 'Cuoi to', difficulty: 'VERY_EASY' },
      { citizen: 'Dap mat na', imposter_hint: 'Trang diem', difficulty: 'HARD' },
    ],
  },
  {
    id: 'jobs',
    name: 'Nghe nghiep',
    icon: 'briefcase',
    pairs: [
      { citizen: 'Bac si', imposter_hint: 'Y ta', difficulty: 'VERY_EASY' },
      { citizen: 'Giao vien', imposter_hint: 'Hoc sinh', difficulty: 'VERY_EASY' },
      { citizen: 'Cong an', imposter_hint: 'Toi pham', difficulty: 'EASY' },
      { citizen: 'Dau bep', imposter_hint: 'Nguoi phuc vu', difficulty: 'EASY' },
      { citizen: 'Hoa si', imposter_hint: 'Ca si', difficulty: 'EASY' },
      { citizen: 'Tho xay', imposter_hint: 'Kien truc su', difficulty: 'HARD' },
      { citizen: 'Phi cong', imposter_hint: 'Tiep vien hang khong', difficulty: 'HARD' },
      { citizen: 'Nong dan', imposter_hint: 'Cong nhan', difficulty: 'EASY' },
      { citizen: 'Lap trinh vien', imposter_hint: 'Gamer', difficulty: 'HARD' },
      { citizen: 'Shipper', imposter_hint: 'Tai xe cong nghe', difficulty: 'EASY' },
      { citizen: 'Tho cat toc', imposter_hint: 'Tho trang diem', difficulty: 'HARD' },
      { citizen: 'Van dong vien', imposter_hint: 'Huan luyen vien', difficulty: 'HARD' },
    ],
  },
  {
    id: 'animals',
    name: 'Dong vat',
    icon: 'dog',
    pairs: [
      { citizen: 'Con khi', imposter_hint: 'Con vuon', difficulty: 'VERY_EASY' },
      { citizen: 'Con voi', imposter_hint: 'Con ho', difficulty: 'VERY_EASY' },
      { citizen: 'Con tho', imposter_hint: 'Con rua', difficulty: 'VERY_EASY' },
      { citizen: 'Chim canh cut', imposter_hint: 'Con vit', difficulty: 'EASY' },
      { citizen: 'Con ran', imposter_hint: 'Con sau', difficulty: 'EASY' },
      { citizen: 'Con lon', imposter_hint: 'Con bo', difficulty: 'VERY_EASY' },
      { citizen: 'Con ga trong', imposter_hint: 'Con vit', difficulty: 'VERY_EASY' },
      { citizen: 'Con cu', imposter_hint: 'Con doi', difficulty: 'HARD' },
      { citizen: 'Con huou cao co', imposter_hint: 'Con ngua', difficulty: 'EASY' },
      { citizen: 'Con bao', imposter_hint: 'Con meo', difficulty: 'EASY' },
      { citizen: 'Con ca sau', imposter_hint: 'Nong noc', difficulty: 'HARD' },
      { citizen: 'Con tom', imposter_hint: 'Con cua', difficulty: 'EASY' },
    ],
  },
  {
    id: 'objects',
    name: 'Do vat',
    icon: 'box',
    pairs: [
      { citizen: 'Cai coc', imposter_hint: 'Cai bat', difficulty: 'VERY_EASY' },
      { citizen: 'Dien thoai', imposter_hint: 'May tinh', difficulty: 'VERY_EASY' },
      { citizen: 'Cai guong', imposter_hint: 'Cua so', difficulty: 'EASY' },
      { citizen: 'Dong ho', imposter_hint: 'Lich', difficulty: 'EASY' },
      { citizen: 'Cai o', imposter_hint: 'Ao mua', difficulty: 'VERY_EASY' },
      { citizen: 'Chia khoa', imposter_hint: 'O khoa', difficulty: 'EASY' },
      { citizen: 'Tu lanh', imposter_hint: 'May giat', difficulty: 'EASY' },
      { citizen: 'Lo vi song', imposter_hint: 'Noi com dien', difficulty: 'HARD' },
      { citizen: 'But bi', imposter_hint: 'But chi', difficulty: 'VERY_EASY' },
      { citizen: 'Thuoc ke', imposter_hint: 'Compa', difficulty: 'VERY_EASY' },
      { citizen: 'Ba lo', imposter_hint: 'Vali', difficulty: 'EASY' },
      { citizen: 'May anh', imposter_hint: 'Ong nhom', difficulty: 'HARD' },
    ],
  },
  {
    id: 'sports',
    name: 'The thao',
    icon: 'sport',
    pairs: [
      { citizen: 'Bong da', imposter_hint: 'Bong chuyen', difficulty: 'VERY_EASY' },
      { citizen: 'Dua boi', imposter_hint: 'Lan', difficulty: 'EASY' },
      { citizen: 'Cau long', imposter_hint: 'Tennis', difficulty: 'EASY' },
      { citizen: 'Bong ro', imposter_hint: 'Bong nem', difficulty: 'EASY' },
      { citizen: 'Dap xe', imposter_hint: 'Chay bo', difficulty: 'VERY_EASY' },
      { citizen: 'Vo thuat', imposter_hint: 'Boxing', difficulty: 'HARD' },
      { citizen: 'Co vua', imposter_hint: 'Co tuong', difficulty: 'HARD' },
      { citizen: 'Ban cung', imposter_hint: 'Ban sung', difficulty: 'HARD' },
      { citizen: 'Leo nui', imposter_hint: 'Dien kinh', difficulty: 'HARD' },
      { citizen: 'Nhay cao', imposter_hint: 'Nhay xa', difficulty: 'HARD' },
      { citizen: 'Cheo thuyen', imposter_hint: 'Luot song', difficulty: 'HARD' },
      { citizen: 'Bong ban', imposter_hint: 'Pickleball', difficulty: 'HARD' },
    ],
  },
];

export const CATEGORIES: Category[] = BASE_CATEGORIES;
export const CHARADES_CATEGORIES: Category[] = BASE_CHARADES_CATEGORIES;
