import { Category } from './types';

const BASE_CATEGORIES: Category[] = [
  {
    id: 'objects',
    name: 'Đồ vật hằng ngày',
    icon: '🏠',
    pairs: [
      { citizen: 'Gấu bông', imposter_hint: 'Búp bê', difficulty: 'VERY_EASY' },
      { citizen: 'Cái cốc', imposter_hint: 'Cái bát', difficulty: 'VERY_EASY' },
      { citizen: 'Bàn chải răng', imposter_hint: 'Khăn mặt', difficulty: 'EASY' },
      { citizen: 'Cặp sách', imposter_hint: 'Hộp bút', difficulty: 'EASY' },
      { citizen: 'Đèn học', imposter_hint: 'Đèn ngủ', difficulty: 'EASY' },
      { citizen: 'Chìa khóa', imposter_hint: 'Ổ khóa', difficulty: 'EASY' },
      { citizen: 'Máy giặt', imposter_hint: 'Tủ lạnh', difficulty: 'EASY' },
      { citizen: 'Lò vi sóng', imposter_hint: 'Nồi cơm điện', difficulty: 'HARD' },
      { citizen: 'Tivi', imposter_hint: 'Máy tính', difficulty: 'EASY' },
      { citizen: 'Quạt trần', imposter_hint: 'Điều hòa', difficulty: 'HARD' },
      { citizen: 'Bình nước', imposter_hint: 'Ấm siêu tốc', difficulty: 'EASY' },
      { citizen: 'Kính mắt', imposter_hint: 'Kính râm', difficulty: 'EASY' },
    ],
  },
  {
    id: 'foods',
    name: 'Ẩm thực',
    icon: '🍕',
    pairs: [
      { citizen: 'Phở', imposter_hint: 'Bún bò', difficulty: 'HARD' },
      { citizen: 'Cơm tấm', imposter_hint: 'Cơm gà', difficulty: 'EASY' },
      { citizen: 'Bánh mì', imposter_hint: 'Hamburger', difficulty: 'EASY' },
      { citizen: 'Trà sữa', imposter_hint: 'Sữa tươi', difficulty: 'EASY' },
      { citizen: 'Kem ốc quế', imposter_hint: 'Sữa chua', difficulty: 'VERY_EASY' },
      { citizen: 'Pizza', imposter_hint: 'Mì Ý', difficulty: 'EASY' },
      { citizen: 'Lẩu', imposter_hint: 'Nướng', difficulty: 'HARD' },
      { citizen: 'Khoai tây chiên', imposter_hint: 'Gà rán', difficulty: 'VERY_EASY' },
      { citizen: 'Xúc xích', imposter_hint: 'Lạp xưởng', difficulty: 'EASY' },
      { citizen: 'Dưa hấu', imposter_hint: 'Dưa lưới', difficulty: 'VERY_EASY' },
      { citizen: 'Muối', imposter_hint: 'Đường', difficulty: 'HARD' },
      { citizen: 'Cà phê sữa', imposter_hint: 'Trà đào', difficulty: 'EASY' },
    ],
  },
  {
    id: 'animals',
    name: 'Động vật',
    icon: '🐾',
    pairs: [
      { citizen: 'Con mèo', imposter_hint: 'Con hổ', difficulty: 'VERY_EASY' },
      { citizen: 'Con chó', imposter_hint: 'Con sói', difficulty: 'EASY' },
      { citizen: 'Con voi', imposter_hint: 'Con hà mã', difficulty: 'EASY' },
      { citizen: 'Con khỉ', imposter_hint: 'Con vượn', difficulty: 'HARD' },
      { citizen: 'Con gà', imposter_hint: 'Con vịt', difficulty: 'VERY_EASY' },
      { citizen: 'Con thỏ', imposter_hint: 'Con chuột', difficulty: 'VERY_EASY' },
      { citizen: 'Cá mập', imposter_hint: 'Cá voi', difficulty: 'EASY' },
      { citizen: 'Con kiến', imposter_hint: 'Con gián', difficulty: 'HARD' },
      { citizen: 'Con ong', imposter_hint: 'Con bướm', difficulty: 'HARD' },
      { citizen: 'Rùa', imposter_hint: 'Ốc sên', difficulty: 'EASY' },
      { citizen: 'Con rắn', imposter_hint: 'Con lươn', difficulty: 'HARD' },
      { citizen: 'Con hươu cao cổ', imposter_hint: 'Con ngựa vằn', difficulty: 'HARD' },
    ],
  },
  {
    id: 'entertainment',
    name: 'Giải trí và phim ảnh',
    icon: '🎬',
    pairs: [
      { citizen: 'Doraemon', imposter_hint: 'Nobita', difficulty: 'VERY_EASY' },
      { citizen: 'Người nhện', imposter_hint: 'Người sắt', difficulty: 'EASY' },
      { citizen: 'Elsa', imposter_hint: 'Anna', difficulty: 'VERY_EASY' },
      { citizen: 'YouTube', imposter_hint: 'TikTok', difficulty: 'EASY' },
      { citizen: 'Rạp chiếu phim', imposter_hint: 'Sân khấu kịch', difficulty: 'HARD' },
      { citizen: 'Ca sĩ', imposter_hint: 'Diễn viên', difficulty: 'EASY' },
      { citizen: 'Harry Potter', imposter_hint: 'Chúa tể nhẫn', difficulty: 'HARD' },
      { citizen: 'Marvel', imposter_hint: 'DC Comics', difficulty: 'HARD' },
      { citizen: 'Superman', imposter_hint: 'Batman', difficulty: 'EASY' },
      { citizen: 'Netflix', imposter_hint: 'Disney Plus', difficulty: 'HARD' },
      { citizen: 'K-pop', imposter_hint: 'V-pop', difficulty: 'HARD' },
      { citizen: 'Guitar', imposter_hint: 'Piano', difficulty: 'EASY' },
    ],
  },
  {
    id: 'knowledge',
    name: 'Kiến thức và đời sống',
    icon: '📚',
    pairs: [
      { citizen: 'Bảng đen', imposter_hint: 'Viên phấn', difficulty: 'VERY_EASY' },
      { citizen: 'Bút chì', imposter_hint: 'Bút bi', difficulty: 'VERY_EASY' },
      { citizen: 'Bác sĩ', imposter_hint: 'Y tá', difficulty: 'EASY' },
      { citizen: 'Công an', imposter_hint: 'Bộ đội', difficulty: 'EASY' },
      { citizen: 'Giáo viên', imposter_hint: 'Giảng viên', difficulty: 'HARD' },
      { citizen: 'Sách giáo khoa', imposter_hint: 'Từ điển', difficulty: 'HARD' },
      { citizen: 'Bản đồ', imposter_hint: 'Quả địa cầu', difficulty: 'HARD' },
      { citizen: 'Tiền mặt', imposter_hint: 'Thẻ ngân hàng', difficulty: 'EASY' },
      { citizen: 'Hộ chiếu', imposter_hint: 'Visa', difficulty: 'HARD' },
      { citizen: 'Email', imposter_hint: 'Thư tay', difficulty: 'HARD' },
      { citizen: 'Wifi', imposter_hint: '4G', difficulty: 'HARD' },
      { citizen: 'Robot', imposter_hint: 'Trí tuệ nhân tạo', difficulty: 'HARD' },
    ],
  },
  {
    id: 'sports',
    name: 'Thể thao',
    icon: '⚽',
    pairs: [
      { citizen: 'Đá bóng', imposter_hint: 'Đá cầu', difficulty: 'VERY_EASY' },
      { citizen: 'Bơi lội', imposter_hint: 'Lặn biển', difficulty: 'EASY' },
      { citizen: 'Cầu lông', imposter_hint: 'Tennis', difficulty: 'EASY' },
      { citizen: 'Bóng rổ', imposter_hint: 'Bóng chuyền', difficulty: 'EASY' },
      { citizen: 'Chạy bộ', imposter_hint: 'Đi bộ', difficulty: 'VERY_EASY' },
      { citizen: 'Đạp xe', imposter_hint: 'Đua xe máy', difficulty: 'EASY' },
      { citizen: 'Tập gym', imposter_hint: 'Yoga', difficulty: 'HARD' },
      { citizen: 'Boxing', imposter_hint: 'Vật', difficulty: 'HARD' },
      { citizen: 'Golf', imposter_hint: 'Bida', difficulty: 'HARD' },
      { citizen: 'Cờ vua', imposter_hint: 'Cờ tướng', difficulty: 'EASY' },
      { citizen: 'Bắn cung', imposter_hint: 'Bắn súng', difficulty: 'HARD' },
      { citizen: 'Nhảy cao', imposter_hint: 'Nhảy xa', difficulty: 'HARD' },
    ],
  },
];

const BASE_CHARADES_CATEGORIES: Category[] = [
  {
    id: 'actions',
    name: 'Hành động',
    icon: '🏃',
    pairs: [
      { citizen: 'Đánh răng', imposter_hint: 'Rửa mặt', difficulty: 'VERY_EASY' },
      { citizen: 'Quét nhà', imposter_hint: 'Lau nhà', difficulty: 'VERY_EASY' },
      { citizen: 'Nấu ăn', imposter_hint: 'Rửa bát', difficulty: 'EASY' },
      { citizen: 'Ngủ gật', imposter_hint: 'Ngáp', difficulty: 'EASY' },
      { citizen: 'Bơi lội', imposter_hint: 'Chèo thuyền', difficulty: 'EASY' },
      { citizen: 'Chụp ảnh', imposter_hint: 'Livestream', difficulty: 'HARD' },
      { citizen: 'Tập gym', imposter_hint: 'Chạy bộ', difficulty: 'EASY' },
      { citizen: 'Đi mua sắm', imposter_hint: 'Đi ship hàng', difficulty: 'HARD' },
      { citizen: 'Lái ô tô', imposter_hint: 'Lái xe máy', difficulty: 'VERY_EASY' },
      { citizen: 'Nhảy múa', imposter_hint: 'Tập thể dục', difficulty: 'EASY' },
      { citizen: 'Khóc nhè', imposter_hint: 'Cười to', difficulty: 'VERY_EASY' },
      { citizen: 'Đắp mặt nạ', imposter_hint: 'Trang điểm', difficulty: 'HARD' },
    ],
  },
  {
    id: 'jobs',
    name: 'Nghề nghiệp',
    icon: '💼',
    pairs: [
      { citizen: 'Bác sĩ', imposter_hint: 'Y tá', difficulty: 'VERY_EASY' },
      { citizen: 'Giáo viên', imposter_hint: 'Học sinh', difficulty: 'VERY_EASY' },
      { citizen: 'Công an', imposter_hint: 'Tội phạm', difficulty: 'EASY' },
      { citizen: 'Đầu bếp', imposter_hint: 'Người phục vụ', difficulty: 'EASY' },
      { citizen: 'Họa sĩ', imposter_hint: 'Ca sĩ', difficulty: 'EASY' },
      { citizen: 'Thợ xây', imposter_hint: 'Kiến trúc sư', difficulty: 'HARD' },
      { citizen: 'Phi công', imposter_hint: 'Tiếp viên hàng không', difficulty: 'HARD' },
      { citizen: 'Nông dân', imposter_hint: 'Công nhân', difficulty: 'EASY' },
      { citizen: 'Lập trình viên', imposter_hint: 'Gamer', difficulty: 'HARD' },
      { citizen: 'Shipper', imposter_hint: 'Tài xế công nghệ', difficulty: 'EASY' },
      { citizen: 'Thợ cắt tóc', imposter_hint: 'Thợ trang điểm', difficulty: 'HARD' },
      { citizen: 'Vận động viên', imposter_hint: 'Huấn luyện viên', difficulty: 'HARD' },
    ],
  },
  {
    id: 'animals',
    name: 'Động vật',
    icon: '🐶',
    pairs: [
      { citizen: 'Con khỉ', imposter_hint: 'Con vượn', difficulty: 'VERY_EASY' },
      { citizen: 'Con voi', imposter_hint: 'Con hổ', difficulty: 'VERY_EASY' },
      { citizen: 'Con thỏ', imposter_hint: 'Con rùa', difficulty: 'VERY_EASY' },
      { citizen: 'Chim cánh cụt', imposter_hint: 'Con vịt', difficulty: 'EASY' },
      { citizen: 'Con rắn', imposter_hint: 'Con sâu', difficulty: 'EASY' },
      { citizen: 'Con lợn', imposter_hint: 'Con bò', difficulty: 'VERY_EASY' },
      { citizen: 'Con gà trống', imposter_hint: 'Con vịt', difficulty: 'VERY_EASY' },
      { citizen: 'Con cú', imposter_hint: 'Con dơi', difficulty: 'HARD' },
      { citizen: 'Con hươu cao cổ', imposter_hint: 'Con ngựa', difficulty: 'EASY' },
      { citizen: 'Con báo', imposter_hint: 'Con mèo', difficulty: 'EASY' },
      { citizen: 'Con cá sấu', imposter_hint: 'Nòng nọc', difficulty: 'HARD' },
      { citizen: 'Con tôm', imposter_hint: 'Con cua', difficulty: 'EASY' },
    ],
  },
  {
    id: 'objects',
    name: 'Đồ vật',
    icon: '📦',
    pairs: [
      { citizen: 'Cái cốc', imposter_hint: 'Cái bát', difficulty: 'VERY_EASY' },
      { citizen: 'Điện thoại', imposter_hint: 'Máy tính', difficulty: 'VERY_EASY' },
      { citizen: 'Cái gương', imposter_hint: 'Cửa sổ', difficulty: 'EASY' },
      { citizen: 'Đồng hồ', imposter_hint: 'Lịch', difficulty: 'EASY' },
      { citizen: 'Cái ô', imposter_hint: 'Áo mưa', difficulty: 'VERY_EASY' },
      { citizen: 'Chìa khóa', imposter_hint: 'Ổ khóa', difficulty: 'EASY' },
      { citizen: 'Tủ lạnh', imposter_hint: 'Máy giặt', difficulty: 'EASY' },
      { citizen: 'Lò vi sóng', imposter_hint: 'Nồi cơm điện', difficulty: 'HARD' },
      { citizen: 'Bút bi', imposter_hint: 'Bút chì', difficulty: 'VERY_EASY' },
      { citizen: 'Thước kẻ', imposter_hint: 'Compa', difficulty: 'VERY_EASY' },
      { citizen: 'Ba lô', imposter_hint: 'Vali', difficulty: 'EASY' },
      { citizen: 'Máy ảnh', imposter_hint: 'Ống nhòm', difficulty: 'HARD' },
    ],
  },
  {
    id: 'sports',
    name: 'Thể thao',
    icon: '⚽',
    pairs: [
      { citizen: 'Bóng đá', imposter_hint: 'Bóng chuyền', difficulty: 'VERY_EASY' },
      { citizen: 'Đua bơi', imposter_hint: 'Lặn', difficulty: 'EASY' },
      { citizen: 'Cầu lông', imposter_hint: 'Tennis', difficulty: 'EASY' },
      { citizen: 'Bóng rổ', imposter_hint: 'Bóng ném', difficulty: 'EASY' },
      { citizen: 'Đạp xe', imposter_hint: 'Chạy bộ', difficulty: 'VERY_EASY' },
      { citizen: 'Võ thuật', imposter_hint: 'Boxing', difficulty: 'HARD' },
      { citizen: 'Cờ vua', imposter_hint: 'Cờ tướng', difficulty: 'HARD' },
      { citizen: 'Bắn cung', imposter_hint: 'Bắn súng', difficulty: 'HARD' },
      { citizen: 'Leo núi', imposter_hint: 'Điền kinh', difficulty: 'HARD' },
      { citizen: 'Nhảy cao', imposter_hint: 'Nhảy xa', difficulty: 'HARD' },
      { citizen: 'Chèo thuyền', imposter_hint: 'Lướt sóng', difficulty: 'HARD' },
      { citizen: 'Bóng bàn', imposter_hint: 'Pickleball', difficulty: 'HARD' },
    ],
  },
];

export const CATEGORIES: Category[] = BASE_CATEGORIES;
export const CHARADES_CATEGORIES: Category[] = BASE_CHARADES_CATEGORIES;

